force-app/main/default/objects/Artifact__c/Artifact__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artifact__c/fields/Artifact_Repository__c.field-meta.xml
<CustomField>
    <fullName>Artifact_Repository__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This is Repository where the Artifact can be stored, in the master branch</inlineHelpText>
    <label>Package Repository</label>
    <referenceTo>Git_Repository__c</referenceTo>
    <relationshipName>Artifacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artifact__c/fields/Artifact_Version__c.field-meta.xml
<CustomField>
    <fullName>Artifact_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Package Version</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Artifact_Version__c.Artifact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Artifact_Version__c</referenceTo>
    <relationshipName>Artifacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artifact__c/fields/Package_Type__c.field-meta.xml
<CustomField>
    <fullName>Package_Type__c</fullName>
    <inlineHelpText>For detailed information : https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_plan_pkg_types.htm</inlineHelpText>
    <label>Package Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unlocked</fullName>
                <default>true</default>
                <label>Unlocked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artifact__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artifact__c/recordTypes/Package_Artifact.recordType-meta.xml
<RecordType>
    <fullName>Package_Artifact</fullName>
    <active>true</active>
    <description>Salesforce Unlocked and Second-Generation Managed Package</description>
    <label>Salesforce Package</label>
</RecordType>

force-app/main/default/objects/Artifact_Version__c/Artifact_Version__c.object-meta.xml
<CustomObject>
    <label>Package Version</label>
    <nameField>
        <label>Artifact Versions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Package_t.cls
@IsTest
public class Package_t extends DomainBuilder {
    public Package_t() {
        super(Artifact__c.SObjectType);
    }

    public Package_t name(String name) {
        return (Package_t) set(Artifact__c.Name, name);
    }

    public Package_t pipelineId(Id pipelineId) {
        return (Package_t) set(Artifact__c.Pipeline__c, pipelineId);
    }

    public Package_t repositoryId(Id repositoryId) {
        return (Package_t) set(Artifact__c.Artifact_Repository__c, repositoryId);
    }

    public Package_t packageType(String packageType) {
        return (Package_t) set(Artifact__c.Package_Type__c, packageType);
    }

    public Package_t recordTypeId(Id recordTypeId) {
        return (Package_t) set(Artifact__c.RecordTypeId, recordTypeId);
    }

    public Package_t packageArtifactRecordType() {
        return recordTypeId(SObjectType.Artifact__c.getRecordTypeInfosByDeveloperName().get('Package_Artifact').getRecordTypeId());
    }

    public Package_t add(PackageVersion version) {
        return (Package_t) version.setParent(Artifact_Version__c.Artifact__c, this);
    }
}