force-app/main/default/objects/Artifact__c/Artifact__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artifact__c/fields/Artifact_Version__c.field-meta.xml
<CustomField>
    <fullName>Artifact_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Package Version</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Artifact_Version__c.Artifact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Artifact_Version__c</referenceTo>
    <relationshipName>Artifacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artifact_Version__c/Artifact_Version__c.object-meta.xml
<CustomObject>
    <label>Package Version</label>
    <nameField>
        <label>Artifact Versions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PackageVersion.cls
@IsTest
public class PackageVersion extends DomainBuilder {
    public PackageVersion() {
        super(Artifact_Version__c.SObjectType);
    }
    
    public PackageVersion packageId(Id packageId) {
        return (PackageVersion) set(Artifact_Version__c.Artifact__c, packageId);
    }

    public PackageVersion versionName(String name) {
        return (PackageVersion) set(Artifact_Version__c.Version_Name__c, name);
    }

    public PackageVersion versionNumber(String versionNumber) {
        return (PackageVersion) set(Artifact_Version__c.Version_number__c, versionNumber);
    }
}