force-app/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <description>A job execution is a representation of a job template execution at a given point in time.</description>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>It is the status of the job execution.</description>
    <inlineHelpText>Status of the job execution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <description>A Job Step is a task that is performed as a result of a job template execution.</description>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A job execution is a representation of a job template execution at a given point in time.</description>
    <inlineHelpText>The job Execution associated with the step</inlineHelpText>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The latest result associated with the job step.</description>
    <inlineHelpText>The latest result associated with the job step.</inlineHelpText>
    <label>Last Result</label>
    <referenceTo>Result__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Job Step.</description>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
  IF(IsSkipped__c , &apos;Skipped&apos;,
    IF(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c))))</formula>
    <inlineHelpText>The status of the Job Step.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/Sub_Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Sub_Job_Execution__c</fullName>
    <description>Technical field. Not available in the page/layout.</description>
    <inlineHelpText>The Id of the related job execution that performs additional steps and operations, such as running a test.</inlineHelpText>
    <label>Sub Job Execution</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the Job Step.</description>
    <inlineHelpText>Type of the Job Step.</inlineHelpText>
    <label>Behaviour</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <description>A unified place to look for job results when working with automations such as functions or Salesforce flows.</description>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Result__c/fields/JobStep__c.field-meta.xml
<CustomField>
    <fullName>JobStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this field points to the Job Step. (note that Job Step and Function can be populated at the same time).</description>
    <inlineHelpText>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this field points to the Job Step. (note that Job Step and Function can be populated at the same time).</inlineHelpText>
    <label>Job Step</label>
    <referenceTo>JobStep__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Result__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <description>This status is used to track the current job activity.</description>
    <inlineHelpText>This status is used to track the current job activity.</inlineHelpText>
    <label>Progress Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Status of the job execution.</description>
    <inlineHelpText>Status of the job execution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CancelExecutionServiceImpl.cls
public with sharing class CancelExecutionServiceImpl {
    private static final String CANCELLED = 'Cancelled';
    private static final String CANCELED = 'Canceled';
    private static final String CANCELLING = 'Cancelling';
    private static final String IN_PROGRESS = 'In Progress';

    // PUBLIC

    public static Jobs.ExecutionResult execute(Id jobId) {
        if (jobId == null) {
            throw new ApplicationException(String.format(Label.MissingRequiredParameters, new List<String>{ 'Job Id' }));
        }

        JobExecution__c job = new JobExecutionsSelector().byIdWithSteps(jobId);

        if (job.JobSteps__r.isEmpty()) {
            throw new ApplicationException(String.format(Label.JobHasNoStep, new List<String>{ 'cancel' }));
        }

        // Note: If the job is not in progress, no need to cancel execution
        if (job.Status__c != IN_PROGRESS) {
            return new Jobs.ExecutionResult(jobId);
        }

        JobStep__c current = currentStep(job.JobSteps__r);
        if (current != null) {
            switch on current?.Type__c {
                when 'Function' {
                    cancelFunction(current);
                }
                when 'Flow' {
                    updateExecutionToCanceled(jobId);
                }
                when 'Manual' {
                    cancelManual(current);
                }
                when 'Test' {
                    cancelTest(current);
                }
                when else {
                    throw new ApplicationException(Label.InvalidStepType);
                }
            }
        }

        return new Jobs.ExecutionResult(jobId);
    }

    // PRIVATE

    private static JobStep__c currentStep(List<JobStep__c> steps) {
        for (JobStep__c step : steps) {
            if (step.Status__c == IN_PROGRESS) {
                return step;
            }
        }

        return null;
    }

    private static void cancelManual(JobStep__c step) {
        Result__c stepResult = new ResultsSelector().byJobStepId(step.Id);

        DML.safeUpdate(
            new Result__c(Id = stepResult.Id, Progress_Status__c = CANCELLED, Status__c = CANCELLED),
            String.format(
                Label.ErrorWhileUpdating,
                new List<String>{ Result__c.SObjectType.getDescribe().getLabel(), 'CancelExecutionServiceImpl.cancelManual' }
            )
        );

        updateExecutionToCanceled(step.JobExecution__c);
    }

    private static void updateExecutionToCanceled(Id jobId) {
        DML.safeUpdate(
            new JobExecution__c(Id = jobId, Status__c = CANCELED),
            String.format(
                Label.ErrorWhileUpdating,
                new List<String>{ JobExecution__c.SObjectType.getDescribe().getLabel(), 'CancelExecutionServiceImpl.updateExecutionToCanceled' }
            )
        );
    }

    private static void cancelTest(JobStep__c step) {
        execute(step.Sub_Job_Execution__c);
        Result__c stepResult = new ResultsSelector().byJobStepId(step.Id);

        DML.safeUpdate(
            new Result__c(Id = stepResult.Id, Progress_Status__c = CANCELLED, Status__c = CANCELLED),
            String.format(
                Label.ErrorWhileUpdating,
                new List<String>{ Result__c.SObjectType.getDescribe().getLabel(), 'CancelExecutionServiceImpl.cancelTest' }
            )
        );

        updateExecutionToCanceled(step.JobExecution__c);
    }

    private static void cancelFunction(JobStep__c step) {
        Result__c stepResult = new ResultsSelector().byJobStepId(step.Id);
        CopadoFunctions.cancel(stepResult.Id);
    }
}