force-app/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <description>A job execution is a representation of a job template execution at a given point in time.</description>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobExecution__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Description of the error if the job has failed.</description>
    <inlineHelpText>Description of the error if the job has failed.</inlineHelpText>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>It is the status of the job execution.</description>
    <inlineHelpText>Status of the job execution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <description>A Job Step is a task that is performed as a result of a job template execution.</description>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A job execution is a representation of a job template execution at a given point in time.</description>
    <inlineHelpText>The job Execution associated with the step</inlineHelpText>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The latest result associated with the job step.</description>
    <inlineHelpText>The latest result associated with the job step.</inlineHelpText>
    <label>Last Result</label>
    <referenceTo>Result__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/ResultDataJson__c.field-meta.xml
<CustomField>
    <fullName>ResultDataJson__c</fullName>
    <description>This field contain any additional step result information once the step has finished, for example for a flow step after the step completes the flow step can put some date which is result of step execution in this field and then use it in next step using {$Job.PrevStep.JSONResult.XXX} dynamic expression</description>
    <inlineHelpText>This field contains any additional step result information once the step has finished.</inlineHelpText>
    <label>Result Data Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Job Step.</description>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
  IF(IsSkipped__c , &apos;Skipped&apos;,
    IF(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c))))</formula>
    <inlineHelpText>The status of the Job Step.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <description>A unified place to look for job results when working with automations such as functions or Salesforce flows.</description>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Result__c/fields/JobStep__c.field-meta.xml
<CustomField>
    <fullName>JobStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this field points to the Job Step. (note that Job Step and Function can be populated at the same time).</description>
    <inlineHelpText>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this field points to the Job Step. (note that Job Step and Function can be populated at the same time).</inlineHelpText>
    <label>Job Step</label>
    <referenceTo>JobStep__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Status of the job execution.</description>
    <inlineHelpText>Status of the job execution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResumeExecutionServiceImpl.cls
public with sharing class ResumeExecutionServiceImpl {
    private JobExecution__c job;

    // PUBLIC

    public static Jobs.ExecutionResult execute(Id jobId) {
        return new ResumeExecutionServiceImpl().resume(jobId);
    }

    public Jobs.ExecutionResult resume(Id jobId) {
        job = new JobExecutionsSelector().byIdWithSteps(jobId);

        if (job == null) {
            throw new ApplicationException(Label.InvalidExecutionId);
        }

        if (job.JobSteps__r.isEmpty()) {
            throw new ApplicationException(String.format(Label.JobHasNoStep, new List<String>{ 'resume' }));
        }

        if (job.Status__c == 'In Progress') {
            throw new ApplicationException(Label.JobInProgress);
        }

        if (!Utilities.checkPermission('Copado_Job_Engine', new Set<Id>{ UserInfo.getUserId() }, false)) {
            String errorMessage = String.format(Label.PermissionSet_InsufficientAccess, new List<String>{ 'Copado Job Engine' });
            new JobEngine(job.Id).finish('Error', errorMessage);

            return new Jobs.ExecutionResult(job.Id);
        }

        clearFailedSteps();

        DML.safeUpdate(
            new JobExecution__c(Id = job.Id, ErrorMessage__c = null, Status__c = 'In Progress'),
            'Could not update a Job Execution object on a Job execution process ( ResumeExecutionServiceImpl.execute class )'
        );

        JobEngine.start(new List<Id>{ job.Id });

        return new Jobs.ExecutionResult(jobId);
    }

    // PRIVATE

    private void clearFailedSteps() {
        List<JobStep__c> stepsToUpdate = new List<JobStep__c>();

        for (JobStep__c step : job.JobSteps__r) {
            if (step.Status__c == 'Failed' || step.Status__c == 'Cancelled') {
                stepsToUpdate.add(new JobStep__c(Id = step.Id, Result__c = null, ResultDataJson__c = null));
            }
        }

        DML.safeUpdate(
            stepsToUpdate,
            'Could not update a Job Step object on a Job execution process ( ResumeExecutionServiceImpl.clearFailedSteps class )'
        );
    }
}