force-app/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <description>A job execution is a representation of a job template execution at a given point in time.</description>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>It is the status of the job execution.</description>
    <inlineHelpText>Status of the job execution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobExecutionMonitorCtrl.cls
public with sharing class JobExecutionMonitorCtrl {
    // PUBLIC

    @AuraEnabled(cacheable=false)
    public static List<Id> getJobIds(Id recordId, String fieldApiName) {
        if (recordId == null || String.isBlank(fieldApiName)) {
            throw new AuraHandledException(
                String.format(
                    Label.MissingRequiredParameters,
                    new List<Object>{ String.join(new List<String>{ 'Record Id', 'Job Execution Field Name' }, ', ') }
                )
            );
        }

        List<JobExecution__c> jobExecutions;

        try {
            String query = String.format(
                'SELECT Id, Name, Status__c FROM JobExecution__c WHERE {0} = :recordId AND Status__c IN (\'Not Started\', \'In Progress\') WITH SECURITY_ENFORCED',
                new List<String>{ fieldApiName }
            );
            jobExecutions = Database.query(query);

            if (jobExecutions.isEmpty()) {
                query = String.format(
                    'SELECT Id, Name, Status__c FROM JobExecution__c WHERE {0} = :recordId WITH SECURITY_ENFORCED ORDER BY SystemModstamp DESC LIMIT 1',
                    new List<String>{ fieldApiName }
                );
                jobExecutions = Database.query(query);
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return new List<Id>(new Map<Id, JobExecution__c>(jobExecutions).keySet());
    }
}