force-app/main/default/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Environment__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <defaultValue>&quot;Salesforce&quot;</defaultValue>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>SFDX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobExecution__c/JobExecution__c.object-meta.xml
<CustomObject>
    <description>A job execution is a representation of a job template execution at a given point in time.</description>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000}</displayFormat>
        <label>Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobExecution__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It is a container used to deploy one or multiple user stories from one environment to another following a designated pipeline.</description>
    <inlineHelpText>Lookup field to the promotion that triggered the execution.</inlineHelpText>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>JobExecutions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>It is the status of the job execution.</description>
    <inlineHelpText>Status of the job execution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <description>A Job Step is a task that is performed as a result of a job template execution.</description>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobStep__c/fields/JobExecution__c.field-meta.xml
<CustomField>
    <fullName>JobExecution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A job execution is a representation of a job template execution at a given point in time.</description>
    <inlineHelpText>The job Execution associated with the step</inlineHelpText>
    <label>Job Execution</label>
    <referenceTo>JobExecution__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/JobTemplate__c.field-meta.xml
<CustomField>
    <fullName>JobTemplate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Name of the job template which initiates the execution of the job step.</description>
    <inlineHelpText>Name of the job template which initiates the execution of the job step.</inlineHelpText>
    <label>Job Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The latest result associated with the job step.</description>
    <inlineHelpText>The latest result associated with the job step.</inlineHelpText>
    <label>Last Result</label>
    <referenceTo>Result__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Job Step.</description>
    <formula>IF(NOT(ISBLANK(JobTemplate__c)), &apos;NA&apos;, 
  IF(IsSkipped__c , &apos;Skipped&apos;,
    IF(ISBLANK(Result__c), &apos;Pending&apos;, TEXT(Result__r.Status__c))))</formula>
    <inlineHelpText>The status of the Job Step.</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/Sub_Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Sub_Job_Execution__c</fullName>
    <description>Technical field. Not available in the page/layout.</description>
    <inlineHelpText>The Id of the related job execution that performs additional steps and operations, such as running a test.</inlineHelpText>
    <label>Sub Job Execution</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the Job Step.</description>
    <inlineHelpText>Type of the Job Step.</inlineHelpText>
    <label>Behaviour</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <description>A job template is a reusable template with a list of steps that can be executed as part of different processes such as a commit, a promotion or a deployment.</description>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobTemplate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Custom&apos;</defaultValue>
    <description>Type of Job Template</description>
    <inlineHelpText>Type of Job Template</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Org__c/Org__c.object-meta.xml
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Result__c/Result__c.object-meta.xml
<CustomObject>
    <description>A unified place to look for job results when working with automations such as functions or Salesforce flows.</description>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Result__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <description>API name of the job that triggered the result. This information can be used for reporting purposes.</description>
    <inlineHelpText>API name of the job that triggered the result. This information can be used for reporting purposes.</inlineHelpText>
    <label>Job API Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Logger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Result__c/fields/JobStep__c.field-meta.xml
<CustomField>
    <fullName>JobStep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this field points to the Job Step. (note that Job Step and Function can be populated at the same time).</description>
    <inlineHelpText>When this result is the outcome of a Job Step, that is executed as part of a Job Template, this field points to the Job Step. (note that Job Step and Function can be populated at the same time).</inlineHelpText>
    <label>Job Step</label>
    <referenceTo>JobStep__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Result__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the promotion that triggered the result.</description>
    <inlineHelpText>Lookup field to the promotion that triggered the result.</inlineHelpText>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Not Started&quot;</defaultValue>
    <description>Status of the job execution.</description>
    <inlineHelpText>Status of the job execution.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResultMonitorLWCHandlerTest.cls
@IsTest
private class ResultMonitorLWCHandlerTest {
    @TestSetup
    private static void setupData() {
        TestUtilities.getAllMultilicense();
        User user = (User) new User_t()
            .assign(new PermissionSetAssignment_t().copadoUser())
            .assign(new PermissionSetAssignment_t().functions())
            .assign(new PermissionSetAssignment_t().jobEngine())
            .assign(new PermissionSetAssignment_t().qualityGatesReadOnly())
            .persist();

        System.runAs(user) {
            new CopadoLicense().user(user).enableAll().persist();
            data();
        }
    }

    @IsTest
    private static void promotionExecutionTest() {
        User user = getRunAsUser();
        System.runAs(user) {
            // Setup
            List<Environment__c> environments = [SELECT Id, Name, Type__c, Platform__c FROM Environment__c];
            Project__c project = [SELECT Id FROM Project__c LIMIT 1];
            new Promotion().projectId(project.Id).sourceEnvId(environments[0].Id).status('Draft').persist();

            Promotion__c promotion = [SELECT Id, Last_Promotion_Execution_Id__c FROM Promotion__c LIMIT 1];
            JobTemplate__c template = [SELECT Id FROM JobTemplate__c LIMIT 1];

            JobExecution__c job = (JobExecution__c) new JobExecution()
                .status('In Progress')
                .template(template.Id)
                .add(
                    new JobStep()
                        .name('step1')
                        .type('Test')
                        .order(1)
                        .configJson('{"type" : "QRT"}')
                        .result(new Result().jobType('Test').status('In Progress'))
                )
                .add(
                    new JobStep()
                        .name('Fill details')
                        .type('Manual')
                        .order(2)
                        .configJson('{"type" : "QRT1"}')
                        .result(new Result().jobType('Manual').status('Not Started'))
                )
                .persist();

            promotion.Last_Promotion_Execution_Id__c = job.Id;
            update promotion;

            JobExecution__c subJob = (JobExecution__c) new JobExecution()
                .status('In Progress')
                .add(
                    new JobStep()
                        .name('Sub Step Manual')
                        .type('Manual')
                        .order(1)
                        .configJson('{"type" : "Manual"}')
                        .result(new Result().jobType('Manual').status('Success'))
                )
                .add(
                    new JobStep()
                        .name('Manual Task Step 2')
                        .type('Manual')
                        .order(2)
                        .configJson('{"type" : "Manual"}')
                        .result(new Result().jobType('Manual').status('In Progress'))
                )
                .persist();

            List<JobStep__c> step = [SELECT Sub_Job_Execution__c FROM JobStep__c WHERE Type__c = 'Test'];
            step[0].Sub_Job_Execution__c = subJob.Id;
            update step;

            // Exercise
            Test.startTest();
            String objectName = (String) SObjectType.Promotion__c.getLocalName();
            String fieldName = (String) SObjectType.Promotion__c.fields.Last_Promotion_Execution_Id__c.getLocalName();

            ResultStatusDetail actualResult = ResultMonitorLWCHandler.result(promotion.Id, objectName, fieldName);
            Test.stopTest();

            // Verify
            Id testStepResult = [SELECT Id FROM Result__c WHERE Status__c = 'In Progress' AND Job_Type__c = 'Manual' LIMIT 1].Id;
            Id manualStepResult = [SELECT Id FROM Result__c WHERE Status__c = 'Not Started' AND Job_Type__c = 'Manual' LIMIT 1].Id;

            System.assertEquals('Sample', actualResult.mainTitle, 'Same as promotion template name');
            System.assertEquals(job.Id, actualResult.jobExecutionId, 'Same as job execution id');
            System.assertEquals('step1', actualResult.resultDetails[0].jobStepLabel, 'Same as step name');
            System.assertEquals('Test', actualResult.resultDetails[0].jobStepType, 'Same as step type');
            System.assertEquals(testStepResult, actualResult.resultDetails[0].resultId, 'The result Id is of last step');
            System.assertEquals('Manual', actualResult.resultDetails[1].jobStepType, 'Same as step type');
            System.assertEquals('Not Started', actualResult.resultDetails[1].resultStatus, 'Same as result status');
            System.assertEquals(manualStepResult, actualResult.resultDetails[1].resultId, 'The result id matches');
            System.assertNotEquals(3, actualResult.resultDetails.size(), 'There should be 3 results in the actualResult');
            System.assertEquals(null, actualResult.jobExecutionErrorMessage, 'There is no error message');
        }
    }

    @IsTest
    private static void deploymentExecutionTest() {
        User user = getRunAsUser();
        System.runAs(user) {
            // Setup
            List<Environment__c> environments = [SELECT Id, Name, Type__c, Platform__c FROM Environment__c];
            Project__c project = [SELECT Id FROM Project__c LIMIT 1];
            new Promotion().projectId(project.Id).sourceEnvId(environments[0].Id).status('Draft').persist();

            Promotion__c promotion = [SELECT Id, Last_Deployment_Execution_Id__c FROM Promotion__c LIMIT 1];
            JobTemplate__c template = [SELECT Id FROM JobTemplate__c LIMIT 1];

            JobExecution__c job = (JobExecution__c) new JobExecution()
                .status('In Progress')
                .template(template.Id)
                .add(
                    new JobStep()
                        .name('step1')
                        .type('Function')
                        .order(1)
                        .configJson('{"functionName" : "MockedFunction"}')
                        .result(new Result().jobType('Function').status('In Progress'))
                )
                .add(
                    new JobStep()
                        .name('step2')
                        .type('Test')
                        .order(2)
                        .configJson('{"type" : "QRT"}')
                        .result(new Result().jobType('Test').status('Not Started'))
                )
                .persist();

            promotion.Last_Deployment_Execution_Id__c = job.Id;
            update promotion;

            JobExecution__c subJob = (JobExecution__c) new JobExecution()
                .status('In Progress')
                .add(
                    new JobStep()
                        .name('step1')
                        .type('Function')
                        .order(1)
                        .configJson('{"functionName" : "MockedFunction"}')
                        .result(new Result().jobType('Function').status('In Progress'))
                )
                .persist();

            List<JobStep__c> step = [SELECT Id, Sub_Job_Execution__c FROM JobStep__c WHERE Type__c = 'Test'];
            step[0].Sub_Job_Execution__c = subJob.Id;
            update step;

            // Exercise
            Test.startTest();
            String objectName = (String) SObjectType.Promotion__c.getLocalName();
            String fieldName = (String) SObjectType.Promotion__c.fields.Last_Deployment_Execution_Id__c.getLocalName();

            ResultStatusDetail actualResult = ResultMonitorLWCHandler.result(promotion.Id, objectName, fieldName);
            Test.stopTest();

            // Verify
            System.assertEquals('Sample', actualResult.mainTitle, 'Same as promotion template name');
            System.assertEquals(job.Id, actualResult.jobExecutionId, 'Same as job execution id');
            System.assertEquals('step1', actualResult.resultDetails[0].jobStepLabel, 'Same as step name');
            System.assertEquals('step2', actualResult.resultDetails[1].jobStepLabel, 'Same as step name');
            System.assertEquals('Function', actualResult.resultDetails[0].jobStepType, 'Same as step type');
            System.assertEquals('Test', actualResult.resultDetails[1].jobStepType, 'Same as step type');
            System.assertEquals('Not Started', actualResult.resultDetails[1].resultStatus, 'Same as result status');
            System.assertNotEquals(3, actualResult.resultDetails.size(), 'There should be 3 results in the actualResult');
            System.assertEquals(null, actualResult.jobExecutionErrorMessage, 'As the job is in progress, there is no error message');
        }
    }

    @IsTest
    private static void executionWithJobExecutionId() {
        User user = getRunAsUser();
        System.runAs(user) {
            // Setup
            JobTemplate__c template = [SELECT Id FROM JobTemplate__c LIMIT 1];

            JobExecution__c job = (JobExecution__c) new JobExecution()
                .status('In Progress')
                .template(template.Id)
                .add(
                    new JobStep()
                        .name('step1')
                        .type('Function')
                        .order(1)
                        .configJson('{"functionName" : "MockedFunction"}')
                        .result(new Result().jobType('Function').status('In Progress'))
                )
                .persist();

            // Exercise

            Test.startTest();
            ResultStatusDetail actualResult = ResultMonitorLWCHandler.result(job.Id, '', '');
            Test.stopTest();

            // Verify
            System.assertEquals('Sample', actualResult.mainTitle, 'Title should be JE Name');
            System.assertEquals(job.Id, actualResult.jobExecutionId, 'Same as job execution id');
            System.assertEquals('step1', actualResult.resultDetails[0].jobStepLabel, 'Same as step name');
            System.assertEquals('Function', actualResult.resultDetails[0].jobStepType, 'Same as step type');
            System.assertEquals('In Progress', actualResult.resultDetails[0].resultStatus, 'Same as result status');
            System.assertEquals(1, actualResult.resultDetails.size(), 'There should be 1 result in the actualResult');
        }
    }

    @IsTest
    private static void executionWithoutTemplateTest() {
        User user = getRunAsUser();
        System.runAs(user) {
            // Setup

            JobExecution__c job = (JobExecution__c) new JobExecution()
                .status('In Progress')
                .add(
                    new JobStep()
                        .name('step1')
                        .type('Manual')
                        .order(1)
                        .configJson('{"type" : "QRT1"}')
                        .result(new Result().jobType('Manual').status('Not Started'))
                )
                .persist();

            // Exercise

            Test.startTest();
            String objectName = (String) SObjectType.JobExecution__c.getLocalName();
            String fieldName = (String) SObjectType.JobExecution__c.fields.Id.getLocalName();

            ResultStatusDetail actualResult = ResultMonitorLWCHandler.result(job.Id, objectName, fieldName);
            Test.stopTest();

            // Verify
            System.assertEquals([SELECT Name FROM JobExecution__c WHERE Id = :job.Id].Name, actualResult.mainTitle, 'Title should be JE Name');
            System.assertEquals(job.Id, actualResult.jobExecutionId, 'Same as job execution id');
            System.assertEquals('step1', actualResult.resultDetails[0].jobStepLabel, 'Same as step name');
            System.assertEquals('Manual', actualResult.resultDetails[0].jobStepType, 'Same as step type');
            System.assertEquals('Not Started', actualResult.resultDetails[0].resultStatus, 'Same as result status');
            System.assertEquals(1, actualResult.resultDetails.size(), 'There should be 1 result in the actualResult');
        }
    }

    @IsTest
    private static void promotionWithoutJobExecutionTest() {
        User user = getRunAsUser();
        System.runAs(user) {
            // Setup
            List<Environment__c> environments = [SELECT Id, Name, Type__c, Platform__c FROM Environment__c];
            Project__c project = [SELECT Id FROM Project__c LIMIT 1];
            new Promotion().projectId(project.Id).sourceEnvId(environments[0].Id).status('Draft').persist();

            Promotion__c promotion = [SELECT Id, Last_Promotion_Execution_Id__c FROM Promotion__c LIMIT 1];

            // Exercise
            Test.startTest();
            String objectName = (String) SObjectType.Promotion__c.getLocalName();
            String fieldName = (String) SObjectType.Promotion__c.fields.Last_Promotion_Execution_Id__c.getLocalName();

            ResultStatusDetail actualResult = ResultMonitorLWCHandler.result(promotion.Id, objectName, fieldName);
            Test.stopTest();

            // Verify
            System.assertEquals(null, actualResult.mainTitle, 'The title for result monitor should remain blank');
            System.assertEquals(null, actualResult.jobExecutionId, 'There should be no job execution');
            System.assertEquals(0, actualResult.resultDetails.size(), 'There should be no results in the actualResult');
            System.assertEquals('Not Started', actualResult.jobExecutionStatus, 'Job status should be not started');
            System.assertEquals(null, actualResult.jobTemplateId, 'There should be no job template');
            System.assertEquals('', actualResult.jobExecutionErrorMessage, 'As there is no job, error message is blank');
        }
    }

    @IsTest
    private static void jobExecutionWithErrorMessage() {
        User user = getRunAsUser();
        System.runAs(user) {
            // Setup
            new Function().apiName('MockedFunction').script('echo hi').persist();
            JobTemplate__c template = [SELECT Id FROM JobTemplate__c LIMIT 1];

            JobExecution__c job = (JobExecution__c) new JobExecution()
                .status('Failed')
                .template(template.Id)
                .add(
                    new JobStep()
                        .name('step1')
                        .type('Function')
                        .order(1)
                        .configJson('{"functionName" : "MockedFunction"}')
                        .result(new Result().jobType('Function').status('Failed').errMsg('There was an error'))
                )
                .add(new JobStep().name('step2').type('Function').order(2).configJson('{"functionName" : "MockedFunction"}'))
                .errorMsg('There was an error')
                .persist();

            // Exercise
            Test.startTest();
            String objectName = (String) SObjectType.JobExecution__c.getLocalName();
            String fieldName = (String) SObjectType.JobExecution__c.fields.Id.getLocalName();

            ResultStatusDetail actualResult = ResultMonitorLWCHandler.result(job.Id, objectName, fieldName);
            Test.stopTest();

            // Verify
            System.assertEquals('Sample', actualResult.mainTitle, 'Title should be job template Name');
            System.assertEquals(job.Id, actualResult.jobExecutionId, 'Same as job execution id');
            System.assertEquals('step1', actualResult.resultDetails[0].jobStepLabel, 'Same as step name');
            System.assertEquals('Function', actualResult.resultDetails[0].jobStepType, 'Same as step type');
            System.assertEquals('Failed', actualResult.resultDetails[0].resultStatus, 'Same as result status');
            System.assertEquals('There was an error', actualResult.jobExecutionErrorMessage, 'Same as job error message');
        }
    }

    // HELPER

    private static void data() {
        Personal_Settings__c ps = Personal_Settings__c.getInstance();
        if (String.isBlank(ps.API_Key__c)) {
            ps.API_Key__c = DeployAPI.encryptAPIKey('99999999999999999999');
            upsert ps;
        }

        //Environment creation
        for (Integer i = 0; i < 3; i++) {
            new Environment().name('Environment ' + i).type('Production/Developer').platform('Other');
        }
        new Environment().name('Test Environment 3').type('Production/Developer').platform('Other').persist();
        List<Environment__c> environments = [SELECT Id, Name, Type__c, Platform__c FROM Environment__c ORDER BY CreatedDate];

        // Org Credential validation
        List<Org__c> credentials = [
            SELECT Id, Name, Environment__c, Platform__c, Oauth_Signature__c, Validated_Date__c, Disable_Validation__c, SFDC_Org_ID__c
            FROM Org__c
            WHERE Platform__c = 'Other'
        ];
        for (Org__c org : credentials) {
            org.Username__c = UserInfo.getUserName();
            org.SFDC_Org_ID__c = UserInfo.getOrganizationId() + '_' + UserInfo.getUserId();
            org.Oauth_Signature__c = org.Name;
            org.Validated_Date__c = System.now();
            org.Disable_Validation__c = true;
            break;
        }
        update credentials;

        new JobTemplate().name('Sample');

        // Deployment flow creation
        new Pipeline()
            .active(true)
            .mainBranch('master')
            .setPlatform('Other')
            .add(new Connection().sourceId(environments[0].Id).destinationId(environments[2].Id).branch('dev1'))
            .add(new Connection().sourceId(environments[1].Id).destinationId(environments[2].Id).branch('dev2'))
            .add(new Project().add(new UserStory().status('Approved').credentialId(credentials[0].Id)))
            .persist();
    }

    private static User getRunAsUser() {
        return [SELECT Id, Email FROM User WHERE Profile.Name = 'Standard User' ORDER BY CreatedDate DESC LIMIT 1];
    }
}