force-app/main/default/objects/Promoted_User_Story__c/Promoted_User_Story__c.object-meta.xml
<CustomObject>
    <label>Promoted User Story</label>
    <nameField>
        <label>Promoted User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoted User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Gate_Rule_Condition__c/Quality_Gate_Rule_Condition__c.object-meta.xml
<CustomObject>
    <label>Quality Gate Rule Condition</label>
    <nameField>
        <displayFormat>QGC-{00000}</displayFormat>
        <label>Quality Gate Rule Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Gate Rule Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Gate_Rule_Condition__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>SFDX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Metadata__c/User_Story_Metadata__c.object-meta.xml
<CustomObject>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Metadata__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Action to be performed with the current metadata when committing</description>
    <inlineHelpText>Action to be performed with the current metadata when committing</inlineHelpText>
    <label>Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Metadata__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Represents a grouping of metadata, i.e. vlocity, cpq</description>
    <inlineHelpText>Represents a grouping of metadata, i.e. vlocity, cpq</inlineHelpText>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Metadata__c/fields/JsonInformation__c.field-meta.xml
<CustomField>
    <fullName>JsonInformation__c</fullName>
    <description>Additional values associated with this commit</description>
    <inlineHelpText>Additional values associated with this commit</inlineHelpText>
    <label>Json Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Metadata__c/fields/Metadata_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Metadata_API_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Metadata__c/fields/ModuleDirectory__c.field-meta.xml
<CustomField>
    <fullName>ModuleDirectory__c</fullName>
    <description>Folder where the metadata is allocated</description>
    <inlineHelpText>Folder where the metadata is allocated</inlineHelpText>
    <label>Directory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Metadata__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the metadata</description>
    <inlineHelpText>Type of the metadata</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Metadata__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Metadata</relationshipLabel>
    <relationshipName>User_Story_Metadata</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ACPromotionDeploymentToRunQG.cls
public with sharing virtual class ACPromotionDeploymentToRunQG extends ACPromotionToRunQG {
    // PROTECTED

    protected override AutomationConnector createConnector(Actions.RunTestRequest request) {
        ACPromotionDeploymentToRunQG connector = new ACPromotionDeploymentToRunQG();
        connector.request = request;
        return connector;
    }

    protected override String getEnvironment() {
        Promotion__c promotion = (Promotion__c) actionRecord;
        return promotion.Destination_Environment__c;
    }

    protected override Boolean assertQualityRuleIsMatching() {
        Promotion__c promotion = (Promotion__c) actionRecord;
        Quality.MatchingRulesRequest qualityRequest = new Quality.MatchingRulesRequest();
        qualityRequest.action = ActionConstants.PROMOTION_DEPLOYMENT;
        qualityRequest.pipeline = new FindPipeline().fromObject(promotion);
        qualityRequest.platform = promotion.Platform__c;
        qualityRequest.templateName = new ActionTemplate(ActionConstants.PROMOTION_DEPLOYMENT).promotion(promotion).getApiName();
        qualityRequest.environment = promotion.Destination_Environment__c;
        qualityRequest.metadataChanges = getMetadata(promotion);
        Quality.MatchingRulesResult matchingRulesResult = Quality.matchingRules(qualityRequest);
        for (Quality_Gate_Rule_Condition__c condition : matchingRulesResult.qualityGates) {
            if (condition.Id == automationRule.Quality_Gate_Rule_Condition__c) {
                return true;
            }
        }
        return false;
    }

    // PRIVATE

    private List<User_Story_Metadata__c> getMetadata(Promotion__c promotion) {
        Set<Id> userStories = new Set<Id>();
        for (Promoted_User_Story__c promotedUserStory : promotion.Promoted_User_Stories__r) {
            userStories.add(promotedUserStory.User_Story__c);
        }
        return [
            SELECT
                Id,
                Metadata_API_Name__c,
                Type__c,
                ModuleDirectory__c,
                Action__c,
                Category__c,
                JsonInformation__c,
                User_Story__c,
                User_Story__r.Name
            FROM User_Story_Metadata__c
            WHERE User_Story__c IN :userStories
            WITH USER_MODE
        ];
    }
}