force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Metadata__c/User_Story_Metadata__c.object-meta.xml
<CustomObject>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Metadata__c/fields/Metadata_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Metadata_API_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Metadata__c/fields/ModuleDirectory__c.field-meta.xml
<CustomField>
    <fullName>ModuleDirectory__c</fullName>
    <description>Folder where the metadata is allocated</description>
    <inlineHelpText>Folder where the metadata is allocated</inlineHelpText>
    <label>Directory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Metadata__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the metadata</description>
    <inlineHelpText>Type of the metadata</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Metadata__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Metadata</relationshipLabel>
    <relationshipName>User_Story_Metadata</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UserStoryMetadata.cls
@IsTest
public with sharing class UserStoryMetadata extends DomainBuilder {
    public UserStoryMetadata() {
        super(User_Story_Metadata__c.SObjectType);
    }

    public UserStoryMetadata name(String name) {
        return (UserStoryMetadata) set(User_Story_Metadata__c.Metadata_API_Name__c, name);
    }

    public UserStoryMetadata type(String type) {
        return (UserStoryMetadata) set(User_Story_Metadata__c.Type__c, type);
    }

    public UserStoryMetadata directory(String directory) {
        return (UserStoryMetadata) set(User_Story_Metadata__c.ModuleDirectory__c, directory);
    }

    public UserStoryMetadata userStoryId(Id userStoryId) {
        return (UserStoryMetadata) set(User_Story_Metadata__c.User_Story__c, userStoryId);
    }
}