force-app/main/default/objects/Function__c/Function__c.object-meta.xml
<CustomObject>
    <description>A function is a script that contains a series of commands and can be executed from Copado.</description>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Function__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>The name of the Apex class which is executed after the function has run.</description>
    <inlineHelpText>Name of the Apex Class. The class must implement the MCCallBack interface.</inlineHelpText>
    <label>ApexClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Function__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>Provide a unique API name.</description>
    <externalId>true</externalId>
    <inlineHelpText>Provide a unique API name.</inlineHelpText>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Function__c/fields/Callback_Type__c.field-meta.xml
<CustomField>
    <fullName>Callback_Type__c</fullName>
    <description>Type of Callback selected for the function.</description>
    <inlineHelpText>Type of Callback selected for the function.</inlineHelpText>
    <label>Callback Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ApexClass</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Function__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the function.</description>
    <inlineHelpText>Description of the function.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Function__c/fields/Image_Name__c.field-meta.xml
<CustomField>
    <fullName>Image_Name__c</fullName>
    <defaultValue>&quot;copado-function-core:v1&quot;</defaultValue>
    <description>Name of the Image required to run the function.</description>
    <inlineHelpText>Name of the docker image provided by Copado. Check our documentation site to find all available images.</inlineHelpText>
    <label>Image Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Function__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>A parameter is a piece of information taken from outside the function that the function needs to be executed.</description>
    <inlineHelpText>This is used to validate if all required parameters are set before calling the execution.</inlineHelpText>
    <label>Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Function__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <description>Provide the script with the commands you would like the function to execute.</description>
    <inlineHelpText>Provide the script with the commands you would like the function to execute.</inlineHelpText>
    <label>Script</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Function__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Custom&quot;</defaultValue>
    <description>The type of Copado function such as Custom or Standard.</description>
    <inlineHelpText>Type of Copado function.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Function__c/fields/Worker_Size__c.field-meta.xml
<CustomField>
    <fullName>Worker_Size__c</fullName>
    <description>Picklist field that defines the size of the worker. The available options are S, M, L, and XL.</description>
    <inlineHelpText>Picklist field that defines the size of the worker. The available options are S, M, L, and XL.</inlineHelpText>
    <label>Worker Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <default>true</default>
                <label>S</label>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobStep__c/JobStep__c.object-meta.xml
<CustomObject>
    <description>A Job Step is a task that is performed as a result of a job template execution.</description>
    <label>Job Step</label>
    <nameField>
        <label>Job Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobStep__c/fields/ConfigJson__c.field-meta.xml
<CustomField>
    <fullName>ConfigJson__c</fullName>
    <description>Config Json stores Job step related configuration information, for example in case of manual step it contains manual task assignee and instructions.</description>
    <inlineHelpText>Config Json stores Job step related configuration information, for example in case of manual step it contains manual task assignee and instructions.</inlineHelpText>
    <label>ConfigJson</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/CustomType__c.field-meta.xml
<CustomField>
    <fullName>CustomType__c</fullName>
    <description>Type of the Job Step.</description>
    <inlineHelpText>Type of the Job Step.</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/JobTemplate__c.field-meta.xml
<CustomField>
    <fullName>JobTemplate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Name of the job template which initiates the execution of the job step.</description>
    <inlineHelpText>Name of the job template which initiates the execution of the job step.</inlineHelpText>
    <label>Job Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Job Steps</relationshipLabel>
    <relationshipName>JobSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The order in which the job steps are executed.</description>
    <inlineHelpText>The order in which the job steps are executed.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JobStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the Job Step.</description>
    <inlineHelpText>Type of the Job Step.</inlineHelpText>
    <label>Behaviour</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Function</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobTemplate__c/JobTemplate__c.object-meta.xml
<CustomObject>
    <description>A job template is a reusable template with a list of steps that can be executed as part of different processes such as a commit, a promotion or a deployment.</description>
    <label>Job Template</label>
    <nameField>
        <label>Job Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A description of the job template.</description>
    <inlineHelpText>A description of the job template.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/JobTemplate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Custom&apos;</defaultValue>
    <description>Type of Job Template</description>
    <inlineHelpText>Type of Job Template</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pipeline_Action__c/Pipeline_Action__c.object-meta.xml
<CustomObject>
    <label>Pipeline Action</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Pipeline Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pipeline_Action__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Copado_Actions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pipeline_Action__c/fields/Job_Template__c.field-meta.xml
<CustomField>
    <fullName>Job_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field defines the job template corresponding to the action being configured. If you want to select a different job template for this action in a particular environment, you will override the template set in the pipeline.</inlineHelpText>
    <label>Job Template</label>
    <referenceTo>JobTemplate__c</referenceTo>
    <relationshipLabel>Pipeline Actions</relationshipLabel>
    <relationshipName>Pipeline_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pipeline_Action__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <inlineHelpText>Select the pipeline where this action will be applied.</inlineHelpText>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>Pipeline Actions</relationshipLabel>
    <relationshipName>Pipeline_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/System_Property__c/System_Property__c.object-meta.xml
<CustomObject>
    <description>This is the pipeline/environment/user specific system properties.</description>
    <label>System Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Property__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>This is the unique name of the system property which is used as a reference in dynamic expressions.</description>
    <inlineHelpText>This is the unique name of the system property which is used as a reference in dynamic expressions.</inlineHelpText>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Property__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the pipeline linked to the system property.</description>
    <inlineHelpText>Lookup field to the pipeline linked to the system property.</inlineHelpText>
    <label>Pipeline</label>
    <referenceTo>Deployment_Flow__c</referenceTo>
    <relationshipLabel>System Properties</relationshipLabel>
    <relationshipName>System_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/System_Property__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>This is the value of the system property.</description>
    <inlineHelpText>This is the value of the system property.</inlineHelpText>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/InvocableGeneratePreFetchedVolume.cls
public inherited sharing class InvocableGeneratePreFetchedVolume {
    public class InvocableVariables {
        @InvocableVariable(label='Git Repository Id' required=true)
        public String repoId;
        @InvocableVariable(label='Pipeline Id' required=true)
        public String pipelineId;
        @InvocableVariable(label='Number of Volumes' required=false)
        public Integer numberOfVolumes;
        @InvocableVariable(label='Volume Config' required=false)
        public String volumeConfig;
    }


    @InvocableMethod(label='Generate Pre-Fetched Volume')
    public static void execute(List<InvocableVariables> variables) {
        assertInput(variables[0]);
        Savepoint sp = Database.setSavepoint();

        try {
            fflib_SObjectDomain.getTriggerEvent(Functions.class).disableAll();
            fflib_SObjectDomain.getTriggerEvent(JobStepTrigger.class).disableAll();
            fflib_SObjectDomain.getTriggerEvent(JobTemplateTrigger.class).disableAll();

            System_Property__c systemProperty = new System_Property__c();
            systemProperty.API_Name__c = 'PreFetchedRepository';
            systemProperty.Name = 'PreFetchedRepository';
            systemProperty.Pipeline__c = variables[0].pipelineId;
            systemProperty.Value__c = variables[0].volumeConfig;

            DML.safeInsert(systemProperty, '');

            if(!prefetchFunctionExists()) {
                createPrefetchFunction();
            }

            List<String> actionNames = new List<String> { 'Commit', 'Promotion', 'PromotionDeployment'};
            addPreFetchVolumeStepsOnActionTemplates(variables[0].pipelineId, actionNames);

            new GeneratePreFetchedVolume(variables[0].repoId, variables[0].pipelineId).execute();

            fflib_SObjectDomain.getTriggerEvent(Functions.class).enableAll();
            fflib_SObjectDomain.getTriggerEvent(JobStepTrigger.class).enableAll();
            fflib_SObjectDomain.getTriggerEvent(JobTemplateTrigger.class).enableAll();
        } catch (Exception ex) {
            Database.rollback(sp);
            throw new ApplicationException(ex.getMessage());
        }
    }


    private static Boolean prefetchFunctionExists() {
        List<Function__c> result = [SELECT Id FROM Function__c WHERE API_Name__c = 'create_prefetched_volume' WITH USER_MODE];

        return !result.isEmpty();
    }


	private static void createPrefetchFunction() {
        Function__c function = new Function__c();
        function.Type__c = 'Standard';
        function.Worker_Size__c = 'M';
        function.Callback_Type__c = 'ApexClass';
        function.Name = 'create_prefetched_volume';
        function.ApexClass__c = String.isNotBlank(Settings.ns) ? 'copado.GeneratePreFetchedVolume' : 'GeneratePreFetchedVolume';
        function.API_Name__c = 'create_prefetched_volume';
        function.Image_Name__c = 'copado-function-core:v1';
        function.Description__c = 'A generic function to prefetch and initiate a Git Repository';
        function.Parameters__c = '[ { "required" : true, "name" : "git_json", "defaultValue" : "{$Context.Repository.Credential}" }, { "name" : "volumeId", "defaultValue" : "" }, { "name" : "settingId", "defaultValue" : "" }, {"name" : "branches", "defaultValue" : "{$Context.Apex.PipelineBranches}"} ]';
        function.Script__c = script();

        insert as user function;
	}


    private static String script() {
        String result = 'mkdir -p /app/repository  \n' +
                        'cd /app/repository  \n' +
                        'git config --global core.preloadindex true || true \n' +
                        'git config --global checkout.workers 8 || true \n' +
                        'git config --global core.checkStat minimal || true \n' +
                        'git config --global core.trustctime true || true \n' +
                        'echo $branches \n' +
                        '# fetch all branches and silently ignore in case the remote branch does not exists \n'+
                        'for branch in ${branches//,/ } \n' +
                        'do \n' +
                        '    time copado-git-get $branch || true \n' +
                        'done \n' +
                        'RESULT_JSON=$(cat <<-END \n' +
                            '{ \n' +
                                '"volumeId": "${volumeId}", \n' +
                                '"settingId": "${settingId}" \n' +
                            '} \n' +
                            'END ) \n' +
                        'git config --local core.preloadindex true || true \n' +
                        'git config --local checkout.workers 8 || true \n' +
                        'git config --local core.checkStat minimal || true \n' +
                        'git config --local core.trustctime true || true \n' +
                        'copado -p "Finished" --result-data "$RESULT_JSON"';

        return result;
    }


	private static void addPreFetchVolumeStepsOnActionTemplates(Id pipelineId, List<String> actionNames) {
        List<Pipeline_Action__c> actions = [SELECT Id, Job_Template__c, Action__c, Pipeline__c FROM Pipeline_Action__c where Pipeline__c = :pipelineId AND Action__c IN :actionNames WITH USER_MODE];

        Map<Id, Boolean> hasPrefetchedStepByTemplateId = hasPrefetchedStepByTemplateId(actions);

        List<JobStep__c> prefetchVolumeSteps = new List<JobStep__c>();

        for(Pipeline_Action__c action : actions) {
            if(hasPrefetchedStepByTemplateId.get(action.Job_Template__c) != true) {
                hasPrefetchedStepByTemplateId.put(action.Job_Template__c, true);
                prefetchVolumeSteps.add(asPrefetchStep(action.Job_Template__c));
            }
        }

        DML.insertAsSystem(prefetchVolumeSteps, '');
	}


	private static JobStep__c asPrefetchStep(Id templateId) {
        String flowName = String.isNotBlank(Settings.ns) ? 'copado.Add_Pre_fetched_volume' : 'Add_Pre_fetched_volume';
        JobStep__c result = new JobStep__c();
        result.Order__c = 0;
        result.Type__c = 'Flow';
        result.JobTemplate__c = templateId;
        result.Name = 'Use Prefetched Volume';
        result.CustomType__c = 'Salesforce Flow';
        result.ConfigJson__c = '{"flowName":"' + flowName + '","parameters":[]}';

        return result;
	}

	private static Map<Id, Boolean> hasPrefetchedStepByTemplateId(List<Pipeline_Action__c> actions) {
        Map<Id, Boolean> result = new Map<Id, Boolean>();

        Set<Id> templateIds = new Set<Id>();

        for(Pipeline_Action__c action : actions) {
            templateIds.add(action.Job_Template__c);
        }

        for(JobStep__c step : [SELECT Id, JobTemplate__c FROM JobStep__c WHERE JobTemplate__c IN :templateIds AND Name = 'Use Prefetched Volume' WITH USER_MODE]) {
            result.put(step.JobTemplate__c, true);
        }

        return result;
	}

	private static void assertInput(InvocableGeneratePreFetchedVolume.InvocableVariables input) {
        Map<String, Object> valueMap = (Map<String, Object>) JSON.deserializeUntyped(input.volumeConfig);

        Integer TWO_HOURS = 7200;
        Integer TWENTY_FOUR_HOURS = 86400;

        Integer ttl = (Integer) valueMap.get('ttl');
        Integer volumeSize = (Integer) valueMap.get('volumeSize');
        Integer volumeAmount = (Integer) valueMap.get('volumeAmount');
        List<InvocableGetPrefetchedVolumeLimit.PreFetchLimit> limits = InvocableGetPrefetchedVolumeLimit.execute();

        if(volumeSize < 2 || volumeSize > 24) {
            throw new ApplicationException('Storage size is out of range. Supported values are 2 GB to 24 GB.');
        }

        if(ttl < TWO_HOURS || ttl > TWENTY_FOUR_HOURS) {
            throw new ApplicationException('Expiration time is out of range. Supported values are 2 Hrs to 24 Hrs.');
        }

        if(volumeAmount < 1 || volumeAmount > limits[0].availableVolumes) {
            throw new ApplicationException('Amount of pre-cloned workers exceeds the limits available in the organization, Supported values are 1 to ' + limits[0].availableVolumes + ' workers.');
        }
    }
}